### ISSUE TITLE
Preparar tutolrial Maven

### ISSUE THREAD

**Issue by JoseCarlosFdez** [JoseCarlosFdez/ISO24-ISO2-B01#1]
De acuerdo al acta de la reunión https://github.com/JoseCarlosFdez/ISO24-ISO2-B01/wiki/Actas-de-las-reuniones se acuerda que Carlos y Pablo preparen el tutorial de Maven para el 20 de Octubre

**Comment by Carlos-SD4** [comment]
Estamos trabajando en ello.
