### ISSUE TITLE
Iteración 1 - Requisitos

### ISSUE THREAD

**Issue by JoseCarlosFdez** [JoseCarlosFdez/ISO24-ISO2-B01#2]
Según el acta de la reunión ( https://github.com/JoseCarlosFdez/ISO24-ISO2-B01/wiki/3‐Actas-de-las-reuniones#acta-reunión-14-10-2024 ) hemos asignado la tarea de requisitos a Daniel que tendrá de plazo hasta el martes a las 23:59 (15/10/2024  23:59).

**Comment by Dmedina-coder** [comment]
Comienzo la fase de análisis de requisitos

**Comment by Dmedina-coder** [comment]
Analizamos el caso de uso "Definir dominios de datos"

**Comment by Dmedina-coder** [comment]
Requisitos finalizados:
- establecer estructura de datos
- establecer tipo de dato
- establecer BBDD contenedora
- establecer forma de relacionar los datos
