### ISSUE TITLE
Componenete 3 - Análisis

### ISSUE THREAD

**Issue by JoseCarlosFdez** [JoseCarlosFdez/ISO24-ISO2-B01#26]
Según el acta de la reunión ( https://github.com/JoseCarlosFdez/ISO24-ISO2-B01/wiki/3%E2%80%90Actas-de-las-reuniones#acta-reuni%C3%B3n-04-11-2024 ) hemos asignado la tarea de Análisis a José Carlos y Javier Garzas que tendrá de plazo hasta el jueves a las 23:59 (07/11/2024 23:59).

**Comment by JavierGarzas** [comment]
Empezamos con la parte de análisis del componete3-iteración 5

**Comment by JavierGarzas** [comment]
terminado vel trabajo
