### ISSUE TITLE
Iteración 1 - Análisis

### ISSUE THREAD

**Issue by JoseCarlosFdez** [JoseCarlosFdez/ISO24-ISO2-B01#3]
Según el acta de la reunión ( https://github.com/JoseCarlosFdez/ISO24-ISO2-B01/wiki/3%E2%80%90Actas-de-las-reuniones#acta-reuni%C3%B3n-14-10-2024 )
 hemos asignado la tarea de Análisis a Pablo y Javier P que tendrá de plazo hasta el miércoles a las 23:59 (16/10/2024 23:59) y empezará cuando los requisitos finalicen.

**Comment by cxrbxyx** [comment]
Comenzamos la fase de análisis trabajando en paralelo

**Comment by javier-pardo4** [comment]
Fase de análisis terminada, resultado:
![Analisis_it_1](https://github.com/user-attachments/assets/418015cc-9746-425e-b86c-aa0dc213ab96)
