### ISSUE TITLE
Componente 5 - Analisis

### ISSUE THREAD

**Issue by JoseCarlosFdez** [JoseCarlosFdez/ISO24-ISO2-B01#39]
Según el acta de la reunión ( https://github.com/JoseCarlosFdez/ISO24-ISO2-B01/wiki/3%E2%80%90Actas-de-las-reuniones#acta-reuni%C3%B3n-11-11-2024 ) hemos asignado la tarea de Análisis a Ángel y Javier Garzás que tendrá de plazo hasta el 15 a las 23:59 (15/11/2024 23:59)

**Comment by agarcial16** [comment]
Empezamos con la fase de análisis

**Comment by JavierGarzas** [comment]
Seguimos trabajando

**Comment by agarcial16** [comment]
Análisis del componente 5 de parte del servidor hecho
![image](https://github.com/user-attachments/assets/e77f118f-99fb-4f82-ba52-c02b644ac2b4)
![image](https://github.com/user-attachments/assets/ff2b63bd-0163-4c8c-bafb-9359cecb8421)

**Comment by JavierGarzas** [comment]
![image](https://github.com/user-attachments/assets/27e899d9-2833-486f-9382-74ed577517c7)

**Comment by JavierGarzas** [comment]
Analisis del componente 5 para el cliente hecho
![image](https://github.com/user-attachments/assets/005192af-16f3-4467-b7db-17b643977fa5)
