### ISSUE TITLE
Iteración 1 - Diseño

### ISSUE THREAD

**Issue by JoseCarlosFdez** [JoseCarlosFdez/ISO24-ISO2-B01#4]
Según el acta de la reunión ( https://github.com/JoseCarlosFdez/ISO24-ISO2-B01/wiki/3%E2%80%90Actas-de-las-reuniones#acta-reuni%C3%B3n-14-10-2024 ) hemos asignado la tarea de diseño a Ángel y Carlos que tendrá de plazo hasta el jueves las 23:59 (17/10/2024 23:59) y empezará cuando el análisis finalice.

**Comment by Carlos-SD4** [comment]
Buenas Tardes, dado que ha finalizado la fase de análisis me pongo esta jornada de tarde con la fase del diseño correspondiente, luego al acabar, mi compañero Ángel se pondrá con ello.

**Comment by Carlos-SD4** [comment]
Hola Buenas, he terminado ya con gran parte del proceso de diseño ya que han sido 6 horas. Le paso a Ángel lo que llevo hecho y el lo termina. Un saludo.

**Comment by agarcial16** [comment]
Buenas, comienzo mi jornada para terminar la fase de diseño.

**Comment by agarcial16** [comment]
Fase de diseño terminada, este es el resultado:
![image](https://github.com/user-attachments/assets/c66aba26-99e0-475c-a3f1-9ea33fffe621)
