### ISSUE TITLE
Componente 6 - Implementacion

### ISSUE THREAD

**Issue by JoseCarlosFdez** [JoseCarlosFdez/ISO24-ISO2-B01#48]
Según el acta de la reunión ( [https://github.com/JoseCarlosFdez/ISO24-ISO2-B01/wiki/3‐Acta-de-Reuniones#reunión-7-25-11-2024](https://github.com/JoseCarlosFdez/ISO24-ISO2-B01/wiki/3%E2%80%90Acta-de-Reuniones#reuni%C3%B3n-7-25-11-2024) ) hemos asignado la tarea de Implementación a Daniel que tendrá de plazo hasta el 29 a las 23:59 (29/11/2024 23:59)

**Comment by Dmedina-coder** [comment]
Comenzamos fase de implementación

**Comment by Dmedina-coder** [comment]
Generada la parte del cliente

**Comment by Dmedina-coder** [comment]
Terminado el componente 6 del servidor
