### ISSUE TITLE
Iteración 1 - Implementación

### ISSUE THREAD

**Issue by JoseCarlosFdez** [JoseCarlosFdez/ISO24-ISO2-B01#5]
Según el acta de la reunión ( https://github.com/JoseCarlosFdez/ISO24-ISO2-B01/wiki/3%E2%80%90Actas-de-las-reuniones#acta-reuni%C3%B3n-14-10-2024 ) hemos asignado la tarea de implementación a Javier G que tendrá de plazo hasta el viernes las 23:59 (18/10/2024 23:59) y empezará cuando el diseño finalicen.

**Comment by JavierGarzas** [comment]
Recibido, ya me han dicho que han terminado diseño asique me pongo a ello

**Comment by JavierGarzas** [comment]
Trabajo terminado
