### ISSUE TITLE
Iteración 2 - Análisis

### ISSUE THREAD

**Issue by JoseCarlosFdez** [JoseCarlosFdez/ISO24-ISO2-B01#8]
Según el acta de la reunión ( https://github.com/JoseCarlosFdez/ISO24-ISO2-B01/wiki/3%E2%80%90Actas-de-las-reuniones#acta-reuni%C3%B3n-21-10-2024 ) hemos asignado la tarea de análisis a Daniel y Pablo que tendrá de plazo hasta el miércoles a las 23:59 (23/10/2024 23:59).

**Comment by cxrbxyx** [comment]
Empezamos el trabajo de análisis

**Comment by Dmedina-coder** [comment]
Subimos a los ficheros compartido el trabajo actual para compartir con el equipo 
![imagen_2024-10-23_175935141](https://github.com/user-attachments/assets/2548db70-cd40-498f-b2fc-099ec2fc2532)

**Comment by cxrbxyx** [comment]
Añadimos diagrama de casos de uso adicional
![Captura desde 2024-10-23 19-07-44](https://github.com/user-attachments/assets/09327bf2-d402-40c9-aee5-6274952eda96)

**Comment by Dmedina-coder** [comment]
Terminamos la fase de análisis en plazo
