### ISSUE TITLE
Iteración 2 - Diseño

### ISSUE THREAD

**Issue by JoseCarlosFdez** [JoseCarlosFdez/ISO24-ISO2-B01#9]
Según el acta de la reunión ( https://github.com/JoseCarlosFdez/ISO24-ISO2-B01/wiki/3%E2%80%90Actas-de-las-reuniones#acta-reuni%C3%B3n-21-10-2024 ) hemos asignado la tarea de diseño a Javier Pardo y Carlos  que tendrá de plazo hasta el Jueves a las 23:59 (24/10/2024 23:59).

**Comment by Carlos-SD4** [comment]
Buenos Días, Javier Pardo y Yo empezamos a trabajar en paralelo con el diseño

**Comment by javier-pardo4** [comment]
Finalizamos la fase de diseño Carlos Sánchez y yo, sacando como resultado el siguiente diagrama de clases:
![Diseño_it2](https://github.com/user-attachments/assets/afe716b8-283e-49fb-b9e9-488af8232ada)
